[package]
name = "mini-quiz"
version = "0.1.0"
edition = "2021"
description = "Terminalden çalışan minik bir quiz oyunu"
authors = ["BSŞ"]

[dependencies]
chrono = "0.4.26"
colorized = "1.0.0"
serde = {version = "1.0.178", features = ["derive"]}
serde_json = "1.0.104"
